# Generated by Django 4.2.18 on 2025-01-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='skills',
            field=models.TextField(help_text='Enter comma-separated values of skills (e.g., Python, Django, JavaScript)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='required_skills',
            field=models.TextField(help_text='Enter comma-separated values of skills (e.g., Python, Django, JavaScript)'),
        ),
    ]
